const data = [
  {
    id: 1,
    name: "cafe",
    brand: "International",
    likes: 1,
    dislikes: 0,
    priceInitial: 30,
    newRelease: true,
    promotions: false,
    discount: 0,
    price: 30,
    photo1: "./src/images/cafe.svg",
  },
  {
    id: 2,
    name: "hamburguesa",
    brand: "burger",
    likes: 10,
    dislikes: 2,
    priceInitial: 120,
    newRelease: false,
    promotions: true,
    discount: 20,
    price: 100,
    photo1: "./src/images/hamburguesa.svg",
  },
  {
    id: 3,
    name: "helado",
    brand: "ice cream",
    likes: 5,
    dislikes: 1,
    priceInitial: 60,
    newRelease: true,
    promotions: false,
    discount: 0,
    price: 60,
    photo1: "./src/images/helado.svg",
  },
  {
    id: 4,
    name: "pizza",
    brand: "picsa",
    likes: 2,
    dislikes: 2,
    priceInitial: 200,
    newRelease: false,
    promotions: true,
    discount: 50,
    price: 150,
    photo1: "./src/images/pizza.svg",
  },
  {
    id: 5,
    name: "rosquilla",
    brand: "kiko",
    likes: 0,
    dislikes: 2,
    priceInitial: 20,
    newRelease: true,
    promotions: false,
    discount: 0,
    price: 20,
    photo1: "./src/images/rosquilla.svg",
  },
  {
    id: 6,
    name: "refresco",
    brand: "soda's",
    likes: 0,
    dislikes: 0,
    priceInitial: 15,
    newRelease: false,
    promotions: true,
    discount: 5,
    price: 10,
    photo1: "./src/images/soda.svg",
  },
];

export default data;
